# Site settings
title: Hub City Developers - Hattiesburg, MS software developers user group
email: Anson.Smith@gmail.com
description: "Starting work on a simple website"
baseurl: ""
url: "http://hubcitydevelopers.com"
twitter_username: anson_smith
github_username:  HubCityDevs

# Build settings
markdown: kramdown
permalink: pretty
